#!/bin/bash

# Retrieve the current month and year
current_month=$(date +%m)
current_year=$(date +%Y)
current_day=$(date +"%-d")
record=$((current_day - 1))

# Define the file path for storing the content
file_path="salawat.txt"

# Get the current year and month
current_year=$(date +%Y)
current_month=$(date +%m)

# Check if the file exists
if [ -f "$file_path" ]; then
    # File exists, read the stored month from the file
    stored_month=$(date -r "$file_path" +%m)

    # Compare the current month with the stored month
    if [ "$current_month" = "$stored_month" ]; then
        # Months are the same, read the content from the file
        response=$(cat "$file_path")
        
    else
        # File exists, but it's not the same month
        api_url="http://api.aladhan.com/v1/calendarByAddress/$current_year/$current_month?address=Tripoli,%20Libya&method=16"
        response=$(curl -s "$api_url")
        echo "$response" > "$file_path"
       
    fi
else
    # File does not exist. Creating a new file
    api_url="http://api.aladhan.com/v1/calendarByAddress/$current_year/$current_month?address=Tripoli,%20Libya&method=16"
    response=$(curl -s "$api_url")
    echo "$response" > "$file_path"
    
fi

# Extract the prayer times for the current day


# Extract the prayer times and timings
date=$(echo "$day_data" | jq -r ".date.readable")

# Retrieve the current time
current_time=$(date +%H:%M)

# Extract the next prayer time and name using jq
next_prayer=$(echo "$response" | jq -r --arg current_time "$current_time" ".data[$record].timings | to_entries | .[] | select(.value > \$current_time and .key != \"Lastthird\" and .key != \"Firstthird\" and .key != \"Midnight\" and .key != \"Imsak\" and .key != \"Sunset\") | .key" | head -n 1)
next_prayer_time=$(echo "$response" | jq -r --arg current_time "$current_time" ".data[$record].timings | to_entries | .[] | select(.value > \$current_time and .key != \"Lastthird\" and .key != \"Firstthird\" and .key != \"Midnight\" and .key != \"Imsak\" and .key != \"Sunset\") | .value" | head -n 1)

# If next prayer is not found for the current day, get the Fajr prayer for the following day
if [[ -z "$next_prayer" ]]; then
    next_prayer=$(echo "$response" | jq -r ".data[$((record + 1))].timings | to_entries | .[] | select(.key == \"Fajr\") | .key" | head -n 1)
    next_prayer_time=$(echo "$response" | jq -r ".data[$((record + 1))].timings | to_entries | .[] | select(.key == \"Fajr\") | .value" | head -n 1)
fi
# Convert the next prayer time to 12-hour format
next_prayer_time=$(date -d "$next_prayer_time" +"%I:%M%p")

# Print the next prayer time and name
echo " 🕌 $next_prayer $next_prayer_time |"